---
server:
  port: 8761
spring:
  application:
    name: service-registry
  config.activate.on-profile: instance1

eureka:
  instance:
    hostname: host1
  client:
    service-url:
      default-zone: http://host2:8762/eureka/
---
server:
  port: 8762
spring:
  application:
    name: service-registry
  config.activate.on-profile: instance2

eureka:
  instance.hostname: host2
  client:
    service-url:
      default-zone: http://host1:8761/eureka/
